### ISSUE TITLE
Where is the code for Physical properties reasoning?

### ISSUE THREAD

**Issue by UHow-Lab** [stevenlsw/physgen#4]
Hi,
It's an amazing work! We like it.
But where is the code for physical properties reasoning?

**Comment by stevenlsw** [comment]
Hi, thanks for your interest! The gpt physics reasoning is now released under [perception](https://github.com/stevenlsw/physgen/tree/main/perception) folder.

**Comment by WesLee88524** [comment]
Hi,
I met an issue when run" python gpt_physic.py --input ../data/domino --output ../outputs/domino" , I tried several times but didn't work. Exactly, I use ChatGPT-4o instead of 4v but gpt_ram.py can work well.
![image](https://github.com/user-attachments/assets/a25ba9fc-aa48-46e3-9691-00d750351c6e)
